[project]
name = "yt-clips-finder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyinstaller>=6.22.3",
    "pyside6>=6.11.1",
    "youtube-transcript-api>=1.2.4",
    "yt-dlp[default]>=2026.7.4",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["INP001", "D100", "CPY001", "S311", "BLE001"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
